### ISSUE TITLE
emit_point appends unspecified tags

### ISSUE THREAD

**Issue by geekifier** [DataDog/dogapi-rb#155]
Consider the following code:

```ruby
require 'dogapi'

options = {
  :dd_tags => 'ping_cluster:ping-dev.bigcorp.com,environment:dev',
  :dd_api_key => 'DD_API_KEY'
}

cluster_stats = {
  :node_count => 0,
  :healthy_node_count => 0,
  :api_failure => 0,
  :replication_required => 0
}

def submit_stats(stats, options)
  dog = Dogapi::Client.new(options[:dd_api_key])
  stats.each do |k, v|
     dog.batch_metrics do
      dog.emit_point("pingf.#{k}", v, :tags => options[:dd_tags].split(','))
    end
  end
end

submit_stats(cluster_stats, options)
```
The code above successfully submits the metrics, and they are tagged with tags specified in `options[:dd_tags]`.

However, in addition to the specified tags, additional tags are appended to the metric:
* host
* environment

How do I prevent the `environment:production` tag from being appended to the metric? The end result of this behavior is that the metric is tagged with both `environment:production` and `environment:dev`.

When dealing with an API, I would expect there to be no surprises as to what the resultant tags are.

**Comment by geekifier** [comment]
OK, this was due to the behavior specified in #42. Appending `host:` to the list of tags "fixed it".

**Comment by zippolyte** [comment]
Hey @geekifier,

This is indeed caused by the behavior of the library to automatically assign the host from which the event is sent when it is not specified. We cannot change that behavior as we don't want to break things for users relying on that behavior.

Please use the workaround of explicitly specified a `nil` or `""` host, as mentioned in #42.
