### ISSUE TITLE
Missing release v1.33.0

### ISSUE THREAD

**Issue by ricobl** [DataDog/dogapi-rb#169]
There's a new [1.33.0 release on rubygems](https://rubygems.org/gems/dogapi/versions/1.33.0) but no version bumps, tags or changelog.

All I could find was a milestone with two merged PRs: https://github.com/DataDog/dogapi-rb/milestone/14?closed=1

Is this version not intended for public use yet?

**Comment by nmuesch** [comment]
Hey @ricobl Apologies for the delay here. I took a look at the release history and it looks like this was added as a release on github - https://github.com/DataDog/dogapi-rb/releases/tag/1.33 (after this issue was opened) as well as had the changelog bumped - https://github.com/DataDog/dogapi-rb/blob/master/CHANGELOG.md#1330--2019-02-13

That being said I'll go ahead and close this issue for now. Thanks for the report!
