### ISSUE TITLE
Ensure that the "tags" parameter is always a list

### ISSUE THREAD

**Issue by LeoCavaille** [DataDog/dogapi-rb#50]
When the user sets the `tags` option with something, ensure that it is just a list of strings (not something nested), it will warn the user that the point tag set is malformed and avoid rejecting it much later in the backend.

**Comment by gzussa** [comment]
This improvements seems to still be valid. @dabcoder is that something you could help fix?

**Comment by zippolyte** [comment]
A utility function to validate the tags has been added. We won't automatically call it for every endpoint, users that want to validate their tags will have to call it explicitly. 
If there is a real need for this, we can re-evaluate and add this to every endpoint.

We didn't want to add this validation to every endpoint that manipulates tags because it can cause some performance drop given that we have to check for every individual tag.
Additionally, given this report never gained much traction, we didn't want to make such a change to every single endpoint and risk breaking things for current users.
