### ISSUE TITLE
is emit_point the correct method to count page views?

### ISSUE THREAD

**Issue by dn** [DataDog/dogapi-rb#75]
I tried `emit_point("foo", 1 )` and `emit_point("bar", 1, { type: 'counter' } )`, but it seems to not have the desired effect - I always get a graph with a flat line showing 1 as value. I'm searching for something identical to `statsd.increment('foo')`.

<img width="558" alt="screenshot 2015-08-20 12 03 33" src="https://cloud.githubusercontent.com/assets/61340/9380894/8010e032-4733-11e5-8df9-7d7273fe152a.png">

**Comment by shamak** [comment]
Looking for this as well. Need a response if possible?

**Comment by yannmh** [comment]
Apologies for the late answer @dn, @shamak.

`dogapi-rb` is basically just a wrapper around Datadog  REST API. What you describe would actually require an aggregator on the client side to compute the appropriate value and periodically flush it to Datadog. 

The easiest way to achieve this would be to use statsd ( `dogstatsd-ruby` in Ruby) instead of the API as Datadog Agent's statsd server does a similar job in term of aggregation. If statsd is not an option for you, we can work on a aggregation tool for `dogapi-rb`: something similar was done in the past for [Datadog's Python library](https://github.com/DataDog/datadogpy) under the name of `ThreadStats`. 

Please let me know your thoughts about it.

**Comment by asmsuechan** [comment]
I solved this problem. Thus I inform how to solve it for someone who hits the same problem.  In order to count page view, you need to handle your Datadog graph, not the application side.

![ss](https://cloud.githubusercontent.com/assets/11307908/23152400/2a6110f2-f845-11e6-92b6-4bd436cb178b.png)

* click `rollup`
* choose `sum`
* input time range into `period` (60 means 1 minute)

**Comment by kristi** [comment]
I think you need to use type 'count' not type 'counter'. Then you get the option to view the metric as a count type.

```
emit_point("bar", 1, { type: 'count' } )
```

You can also change the type of an existing metric by updating the metadata

```
from datadog import initialize, api

options = {
    'api_key': 'API_KEY',
    'app_key': 'APP_KEY'
}
initialize(**options)

metric = 'metric.name.here'
metadata = api.Metadata.get(metric_name=metric)
print(metadata)
metadata['type'] = 'count'
print(metadata)
api.Metadata.update(metric_name=metric, **metadata)
```

**Comment by gzussa** [comment]
Leaving this as closed since solutions where provided and it doesn't seem to be an issue anymore. If that's not the case, feel free to reopen and give more up to date details.
